name: ubuntu-mate-welcome
version: git
version-script: |
  VER=$(grep __VERSION__ ubuntu-mate-welcome | head -n 1 | cut -d'=' -f2 | sed 's/ //g' | sed "s/'//g")
  REV=$(git rev-parse --short HEAD)
  echo $VER-$REV
summary: Welcome screen for Ubuntu MATE
description: |
 A welcome screen for Ubuntu MATE that provides links to helpful
 resources, utilities and a selection of software packages.

confinement: classic

parts:
  # Build a minimal zenity from source, prevents dragging in WebKit et al.
  zenity:
    plugin: autotools
    source: https://git.gnome.org/browse/zenity/snapshot/ZENITY_3_18_1_1.tar.xz
    configflags:
      - --prefix=/usr
    build-packages:
      - gnome-common
      - libgtk-3-dev
      - libnotify-dev
      - yelp-tools
    stage:
      - usr/bin/zenity
      - usr/share/zenity

  ubuntu-mate-welcome:
    plugin: nil
    after:
      - zenity
    #build-attributes:
    #  - no-system-libraries
    build-packages:
      - gettext
      - python3
      - python3-polib
      - rsync
    stage-packages:
      - gir1.2-gtk-3.0
      - gir1.2-notify-0.7
      - gir1.2-webkit2-4.0
      - inxi
      #- parted - is in the standard and ubuntu-core tasks
      #- pciutils - is in the standard task
      - policykit-1
      - python3
      - python3-apt
      - python3-aptdaemon
      - python3-aptdaemon.gtk3widgets
      - python3-gi
      - python3-polib
      - python3-setproctitle
      - python3-software-properties
      #- software-properties-common - in all the Ubuntu flavour tasks
    prepare: |
      # Modify the icon paths for the snap.
      sed -i 's|Icon=software-boutique|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/software-boutique\.svg|' ubuntu-mate-software.desktop
      sed -i 's|Icon=ubuntu-mate|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/ubuntu-mate\.svg|' ubuntu-mate-welcome.desktop
    build: |
      ./welcome-po.py --update-pos
      ./welcome-po.py --install
      ./edgar-allan translate-all
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/ubuntu-mate-welcome/
      rsync -a data/ $SNAPCRAFT_PART_INSTALL/usr/share/ubuntu-mate-welcome/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/
      rsync -a hicolor/ $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/locale
      rsync -a locale/ $SNAPCRAFT_PART_INSTALL/usr/share/locale/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      cp *.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp ubuntu-mate-welcome $SNAPCRAFT_PART_INSTALL/usr/bin/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/ubuntu-mate/
      cp ubuntu-mate-welcome-repository-installer $SNAPCRAFT_PART_INSTALL/usr/lib/ubuntu-mate/
      cp ubuntu-mate-welcome-rpi2-partition-resize $SNAPCRAFT_PART_INSTALL/usr/lib/ubuntu-mate/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
      cp ubuntu-mate-welcome.1 $SNAPCRAFT_PART_INSTALL/usr/share/man/man1

    # The cruft_ filesets define files/directories that can be safely
    # removed from Ubuntu MATE Welcome to reduce the size of the snap.
    # They have been grouped to assist others seeking to shrink the size
    # of Python snaps.
    filesets:
      cruft_apport:
        - -usr/share/apport
      cruft_aspell:
        - -etc/dictionaries-common
        - -usr/bin/*spell*
        - -usr/lib/aspell
        - -usr/lib/ispell
        - -usr/sbin/*aspell*
        - -usr/sbin/*ispell*
        - -usr/share/aspell
        - -usr/share/dict
        - -var/cache/dictionaries-common
        - -var/lib/aspell
        - -var/lib/ispell
        - -var/lib/dictionaries-common
      cruft_binaries:
        - -bin/*.py
        - -bin/html2text
        - -bin/markdown_py
        - -bin/mid3*
        - -bin/moggsplit
        - -bin/mutagen*
        - -bin/pyrsa*
        - -usr/bin/pydoc3*
        - -usr/bin/ucf*
        - -usr/share/apps
      cruft_compilers_and_debuggers:
        - -usr/bin/pdb3*
        - -usr/lib/gcc
        - -usr/lib/valgrind
        - -usr/share/bug
      cruft_debhelper:
        - -usr/bin/dh_*
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/perl5/Debian
      cruft_docs:
        - -usr/share/doc
        - -usr/share/doc-base
      cruft_emacs:
        - -etc/emacs
        - -usr/lib/emacsen-common
        - -usr/share/emacs
        - -var/lib/emacsen-common
      cruft_fonts:
        - -etc/fonts
        - -usr/bin/fc-*
        - -usr/share/fonts
      cruft_gnome:
        - -usr/share/glib-2.0/schemas
        - -usr/share/GConf
      cruft_headers:
        - -usr/include
        - -usr/share/include
      cruft_icons:
        - -usr/share/icons/Adwaita
        - -usr/share/icons/Humanity*
        - -usr/share/icons/LoginIcons
        - -usr/share/icons/ubuntu-mono-*
      cruft_init:
        - -etc/init*
        - -lib/systemd
        - -sbin/cg*
        - -usr/lib/systemd
        - -usr/share/upstart
        - -var/lib/systemd
      cruft_lintian:
        - -usr/share/lintian/overrides
      cruft_man_pages:
        - -usr/share/man
      cruft_meta:
        - -usr/share/pixmaps
        - -usr/share/pkgconfig
      cruft_python_2to3:
        - -usr/bin/2to3*
        - -usr/lib/python*/lib2to3
      cruft_python_distutils:
        - -usr/lib/python*/distutils
      cruft_python_idle:
        - -usr/lib/python*/idlelib
        - -usr/lib/python*/tkinter
        - -usr/share/applications/python3.5.desktop
      cruft_python_pip:
        - -lib/python*/site-packages/pip
      cruft_python_tests:
        - -lib/python*/site-packages/tests
      cruft_python_venv:
        - -usr/lib/python*/venv
      cruft_python_wheel:
        - -lib/python*/site-packages/wheel*
      cruft_x11:
        - -etc/X11
        - -usr/lib/*/dri
        - -usr/share/libdrm
        - -usr/share/X11
    prime:
      - $cruft_apport
      - $cruft_aspell
      - $cruft_binaries
      - $cruft_compilers_and_debuggers
      - $cruft_debhelper
      - $cruft_docs
      - $cruft_emacs
      - $cruft_gnome
      - $cruft_fonts
      - $cruft_headers
      - $cruft_icons
      - $cruft_init
      - $cruft_lintian
      - $cruft_man_pages
      - $cruft_meta
      - $cruft_python_2to3
      - $cruft_python_distutils
      - $cruft_python_idle
      - $cruft_python_pip
      - $cruft_python_tests
      - $cruft_python_venv
      - $cruft_python_wheel
      - $cruft_x11

apps:
  ubuntu-mate-welcome:
    command: usr/bin/ubuntu-mate-welcome
    desktop: usr/share/applications/ubuntu-mate-welcome.desktop
  software-boutique:
    command: usr/bin/ubuntu-mate-welcome --boutique
    desktop: usr/share/applications/ubuntu-mate-software.desktop
